hostconfig:
  dns: 192.180.1.10
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "shawn.lab"
blocks:
  - netmask: 255.255.255.0
    gateway: 192.180.3.254
    ips:
    - ip: 192.180.3.20
      hostname: user1-host1
    - ip: 192.180.3.21
      hostname: user1-host2
    - ip: 192.180.3.22
      hostname: user1-host3
    - ip: 192.180.3.23
      hostname: user1-host4
    - ip: 192.180.3.24
      hostname: user1-host5
    - ip: 192.180.3.25
      hostname: user1-host6
