hostconfig:
  dns: 192.180.1.10
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "shawn.lab"
blocks:
  - netmask: 255.255.255.0
    gateway: 192.180.2.254
    ips:
    - ip: 192.180.2.58
      hostname: admin-lb1
    - ip: 192.180.2.59
      hostname: admin-lb2
