steps:
## CLUSTER CREATE ##

# Create a new cluster with the appropriate configuration for this application
- name: 'gcr.io/cloud-builders/gcloud'
  id: Create Cluster
  waitFor: ['-']
  args: [
    'beta', 'container', 'clusters', 'create', '${_CLUSTER_NAME}',
    '--addons', 'HorizontalPodAutoscaling,HttpLoadBalancing,CloudRun',
    '--machine-type', 'e2-standard-4',
    '--num-nodes', '3',
    '--release-channel', 'regular',
    '--enable-stackdriver-kubernetes',
    '--identity-namespace', '${PROJECT_ID}.svc.id.goog',
    '--enable-ip-alias', 
    '--zone', '${_CLUSTER_LOCATION}'
  ]

