hostconfig:
  dns: 192.180.1.10
  tod: 216.239.35.0
  otherdns:
  - 8.8.8.8
  - 8.8.4.4
  othertod:
  - ntp.ubuntu.com
  searchdomainsfordns:
  - "shawn.lab"
blocks:
  - netmask: 255.255.255.0
    gateway: 192.180.2.254
    ips:
    - ip: 192.180.2.70
      hostname: user-host1
    - ip: 192.180.2.71
      hostname: user-host2
    - ip: 192.180.2.72
      hostname: user-host3
    - ip: 192.180.2.73
      hostname: user-host4
    - ip: 192.180.2.74
      hostname: user-host5
