apiVersion: v1
kind: Service
metadata:
  name: gateway-proxy-svc
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"80":{}}}'
spec:
  selector:
    app: gateway-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
